#!/bin/bash
#
#  FUNCTION: PRINT INFO
Info() {
Col="38;5;129m" # Color code 
echo  -e "\033[$Col\n[INFO]..... $1 \033[0m"
}

# ------------------------------------------------------------------------------------------------------------
# Voxel size (x10)
# Cambiar dimension voxeles de la sequencia de RESTING STATE (rsFMRI)
ls */*rsfMRI_*E?.nii.gz | parallel fslchpixdim  {} 1.17 1.17 12

### BET Estructural T2 
# Reorientando sujetos igual que al atlas
ls */*_T2_Turbo*E?.nii.gz | cut -d . -f 1 | parallel fslswapdim {} x y z {}_sw

# Extraer cerebro
for i in $(ls */*T2_Turbo*_sw.nii.gz);do
	echo $i; 
	fslchpixdim  $i 1.17 1.17 6
	j=$(echo $i | cut -d . -f 1);
	center=$(cluster -i $i -t 10 | sed -n '2{p;q}' | awk '{print int($7)" "int($8)" "int($9)}');

	bet ${i} ${j}_brain.nii.gz -r 75 -c $center -f 0.3 -g 0.25;
	#bet ${j}_brain.nii.gz ${j}_brain.nii.gz -r 75 -c $center -f 0.25 -g -0.25;

	fslchpixdim  $i 1.17 1.17 12
	fslchpixdim ${j}_brain.nii.gz  1.17 1.17 12

done

slicesdir -o $(ls -r */*Turbo*_sw*gz)
rm -rf slicesdir_BET; mv slicesdir/ slicesdir_BET

#------------------------------------------------------------------------------#
# 			REGISTRATION TO ATLAS
nii=$1
out=$2
template=/misc/ernst/rcruces/database/atlas/Tohoku_1mm/brain_1mm.nii.gz
labels=/misc/ernst/rcruces/database/atlas/Tohoku_1mm/labels_1mm.nii.gz
sub=AntsReg
mkdir $sub
# NOTE the atlas is resize to 1x1x1 mm² the following command was used for the labels:
# mrresize cortex.nii.gz -voxel 1,1,1 -interp nearest cortex_1mm.nii.gz
# Valdes Hernandez, P. A., Sumiyoshi, A., Nonaka, H., Haga, R., Aubert Vasquez, E., Ogawa, T., ... & Kawashima, R. (2011). An in vivo MRI template set for morphometry, tissue segmentation, and fMRI localization in rats. Frontiers in neuroinformatics, 5, 26.
# Papp, E. A., Leergaard, T. B., Calabrese, E., Johnson, G. A., & Bjaalie, J. G. (2014). Waxholm Space atlas of the Sprague Dawley rat brain. Neuroimage, 97, 374-386.
# NOTE the atlas is resize to 1x1x1 mm² the following command was used for the labels:
# mrresize cortex.nii.gz -voxel 1,1,1 -interp sinc cortex_1mm_sc.nii.gz


Info "Registering $nii to Tohoku-University Atlas 1x1x1mm, with output name of: $out"

# Affine and warp deformation from T2_SWI to Atlas T2
antsRegistration -d 3 --float 0  -o [${sub}/${out},${sub}/${out}_Warped.nii.gz]  -n Linear  -w [0.005,0.995]  -u 0  -r [$template,$nii,1]  -t Rigid[0.1]  -m MI[$template,$nii,1,32,Regular,0.25]  -c [1000x500x250x100,1e-6,10]  -f 8x4x2x1  -s 3x2x1x0vox  -t Affine[0.1]  -m MI[$template,$nii,1,32,Regular,0.25]  -c [1000x500x250x100,1e-6,10]  -f 8x4x2x1  -s 3x2x1x0vox -t SyN[0.1,3,0]  -m CC[$template,$outnii,1,4]  -c [100x70x50x20,1e-6,10]  -f 8x4x2x1  -s 3x2x1x0vox -v 

Info "Applying inverse transformations to the labels"
cmd "WarpImageMultiTransform 3 $template ${out}_labels_warped.nii.gz -i ${sub}/${out}_0GenericAffine.mat ${sub}/${out}_1InverseWarp.nii.gz -R $outnii --use-NN"

#------------------------------------------------------------------------------#
# 			CONTROL DE CALIDAD DEL REGISTRO AL ATLAS
slicesdir -p $template ${sub}/${out}_Warped.nii.gz


