#!/bin/bash
#
# Aplica una reorientacion general de la imagen y reacomodo de las etiquetas.


#---------------- HELP ----------------#
print_help() {
echo "
Uso:

`basename $0` NIFTI

Reorienta las imagenes estructurales del resonador Bruker. 	



Raul RC
INB, Enero, 2018
raulrcruces@inb.unam.mx

"
}
#---------------- COMMANDS ----------------#
cmd() {
text=$1
echo -e "\033[38;5;208m \nCOMMAND --> $text \033[0m"
echo $($text)
}

#---------------- WARNINGS ----------------#
if [ $# -lt 2 ]
then
	echo -e "\e[0;31m\n[ERROR]... \tRequiere dos argumentos:\n\n\e[0m\t\tInput NIFTI: $1\n\t\tOutname:$2"
	print_help
	exit 1
fi


# --------------------------------------------------------------- # 
# 			Starting Requirements
# --------------------------------------------------------------- # 
 
#---------------- Declaring variables ----------------#
NII=$1
out=$2
tmp=/tmp/reo_$RANDOM
reo=${tmp}/${NII/.nii.gz/reo_.nii.gz}




#---------------- Timer & Beginning ----------------#
aloita=$(date +%s.%N)
echo -e "\033[48;5;22m\n[INIT]... \tReorienting to Atlas space: $NII\n\033[0m"



#---------------- Temporal directory ----------------# 
mkdir $tmp
echo  -e "\033[38;5;45m\n[INFO]... tmp directory: \033[0m"
echo   -e "\033[38;5;208mDIR -->\t $tmp\033[0m"


#---------------- Reorientando al espacio del atlas ----------------#
# Reorienta al espacio estandar
cmd "fslreorient2std $NII $reo"

# Borra las etiquetas
cmd "fslorient -deleteorient $reo"

# Invierte la orietacion x,y
cmd "fslswapdim $reo -x z -y $out"

# Coloca las nuevas etiquetas
cmd "fslorient -setqformcode 1 $out"


#----------- Removes temporal directory -----------#
echo -e "\033[38;5;45m\n[INFO]... Removing temporal files: $tmp\e[0m"
 rm -Rv $tmp


#----------- Outfile -----------#
echo  -e "\033[38;5;45m\n[INFO]... Outfile: ${out} \033[0m"


#----------- Total Time -----------#
lopuu=$(date +%s.%N)
eri=$(echo "$lopuu - $aloita" | bc)
echo -e "\\033[38;5;220m \n TOTAL running time: ${eri} seconds \n \\033[0m"




