#!/bin/bash
#  FUNCTION: PRINT COLOR COMMAND
#
#
help() {
echo -e " 
Uso:   \033[38;5;141m`basename $0`\033[0m  \033[38;5;197m NIFTI_T2.nii.gz \033[0m \033[38;5;197m N \033[0m

	\033[38;5;197mNIFTI\033[0m	Es el archivo NIFTI al que se le aplicaran las funciones.
	\033[38;5;197mN\033[0m	Es el factor por el que se multiplicaran los voxeles (por ejemplo 10).

1. Copia el archivo original
2. Cambia la resolución de los voxeles x10
3. Calcula en centroide de la imagen y genera una mascara binaria basada en él.
4. Aplica limpieza de ruido con non-local means de PIerrick coupe.
5. Biasfield correction de ANTs
"
}


cmd() {
text=$1
echo -e "\033[38;5;130mCOMANDO -->\033[0m \033[38;5;39m$text\033[0m"
eval $text
}
#  FUNCTION: PRINT INFO
Info() {
Col="38;5;129m" # Color code 
echo  -e "\033[$Col\n[INFO]..... $1 \033[0m"
}
#  FUNCTION: PRINT ERROR
Error() {
echo -e "\e[0;31m\n[ERROR]..... $1\n\e[0m"
}

# --------------------------------------------------------------------------------
orig=$1
N=$2

id=`echo $orig | awk -F "." '{print $1}'`
mri=${id}_copia.nii.gz
brain=${id}_brain.nii.gz

# Number of inputs
if [ "$#" -lt 2 ]; then Error "Falta un argumento"; help; exit 0; fi


echo -e "\033[48;5;39m\n[INIT]..... Modifica el tamaño de los voxeles, identifica el centro y crea una máscara binaria de $1 \n\033[0m"

Info "Creando una copia del archivo original"
cmd "cp $orig $mri"

Vox=`mrinfo -vox $mri`
X=`echo $Vox | awk -v n="$N" -F " " '{print $1*n}'`
Y=`echo $Vox | awk -v n="$N" -F " " '{print $2*n}'`
Z=`echo $Vox | awk -v n="$N" -F " " '{print $3*n}'`
Info "Cambiar el tamaño de los Voxeles ($Vox) x $N"
cmd "fslchpixdim  $mri $X $Y $Z"

Info "El centro de $mri es:"
center=$(cluster -i $mri -t 10 | sed -n '2{p;q}' | awk '{print int($7)" "int($8)" "int($9)}');
echo $center

Info "Estima una mascara binaria del cerebro y corta"
cmd "bet $mri $brain -r 75 -c $center -f 0.15 -g 0.25"

# Por qué remuestrea x20 una dimensión???
#cmd "cp $brain tmp_mask.nii.gz"
#cmd "cp $mri tmp_${id}.nii.gz"
#bet ${j}_brain.nii.gz ${j}_brain.nii.gz -r 75 -c $center -f 0.25 -g -0.25;
#Info "Cambia de nuevo el tamaño de los voxeles de $mri y de"
#cmd "fslchpixdim  tmp_${id}.nii.gz 0.802139 10 0.802139"
#cmd "fslchpixdim tmp_mask.nii.gz  0.802139 10 0.802139"

Info "Limpieza de Ruido y Corrección de Campo"
cmd "/misc/ernst/rcruces/git_here/MRI_analytic_tools/Freesurfer_preprocessing/denoiseN4 $brain ${id}_dn4 ."

Info "Creando una mascara binaria del archivo ya corregido ${id}_dn4"
fslmaths ${id}_dn4.nii.gz -bin ${id}_mask.nii.gz

Info "Borra los archivos innecesarios"
cmd "rm $brain $mri"

Info "Para ciertas adquisiciones quiza es necesario rotar el eje-Z:"
echo "mrtransform -flip 2 ${id}_mask.nii.gz ${id}_mask_Z.nii.gz"

