#!/bin/bash

#  FUNCTION: PRINT INFO
Info() {
Col="38;5;129m" # Color code 
echo  -e "\033[$Col\n[INFO]..... $1 \033[0m"
}

# ------------------------------------------------------------------------------------------------------------
# Voxel size (x10)
# Cambiar dimension voxeles de la sequencia de RESTING STATE (rsFMRI)
ls */*rsfMRI_*E?.nii.gz | parallel fslchpixdim  {} 1.17 1.17 12

### BET Estructural T2 
# Reorientando sujetos igual que al atlas
ls */*_T2_Turbo*E?.nii.gz | cut -d . -f 1 | parallel fslswapdim {} x y z {}_sw

# Extraer cerebro
for i in $(ls */*T2_Turbo*_sw.nii.gz);do
	echo $i; 
	fslchpixdim  $i 1.17 1.17 6
	j=$(echo $i | cut -d . -f 1);
	center=$(cluster -i $i -t 10 | sed -n '2{p;q}' | awk '{print int($7)" "int($8)" "int($9)}');

	bet ${i} ${j}_brain.nii.gz -r 75 -c $center -f 0.3 -g 0.25;
	#bet ${j}_brain.nii.gz ${j}_brain.nii.gz -r 75 -c $center -f 0.25 -g -0.25;

	fslchpixdim  $i 1.17 1.17 12
	fslchpixdim ${j}_brain.nii.gz  1.17 1.17 12

done

slicesdir -o $(ls -r */*Turbo*_sw*gz)
rm -rf slicesdir_BET; mv slicesdir/ slicesdir_BET

# ------------------------------------------------------------------------------------------------------------
### T2 brain to ATLAS
# NOTE the atlas is resize to 1x1x1 mm² the following command was used for the labels:
# mrresize cortex.nii.gz -voxel 1,1,1 -interp sinc cortex_1mm_sc.nii.gz

T2_SWI=7_007_SWI_T2star_map_MGE_E7_dn4.nii.gz
sub=swi_7_007
template=/mnt/Data/RAT_fMRI/Templates_Rat/TohokuUniv/brain.nii;

Info "Moving $T2_SWI to REFERENCE $template with output name of: $sub"

# Affine and warp deformation from T2_SWI to Atlas T2
antsRegistration -d 3 --float 0  -o [${sub}/brain_1mm_to_${sub}_,${sub}/brain_1mm_to_${sub}_Warped.nii.gz]  -n Linear  -w [0.005,0.995]  -u 0  -r [$template,$T2_SWI,1]  -t Rigid[0.1]  -m MI[$template,$T2_SWI,1,32,Regular,0.25]  -c [1000x500x250x100,1e-6,10]  -f 8x4x2x1  -s 3x2x1x0vox  -t Affine[0.1]  -m MI[$template,$T2_SWI,1,32,Regular,0.25]  -c [1000x500x250x100,1e-6,10]  -f 8x4x2x1  -s 3x2x1x0vox -t SyN[0.1,3,0]  -m CC[$template,$T2_SWI,1,4]  -c [100x70x50x20,1e-6,10]  -f 8x4x2x1  -s 3x2x1x0vox -v 

# Inverser transformations for Atlas_labels to Native space
WarpImageMultiTransform 3 ../cortex_1mm.nii.gz 7_003_labels_warped.nii.gz -i brain_1mm_to_swi_7_007_0GenericAffine.mat brain_1mm_to_swi_7_007_1InverseWarp.nii.gz -R ../7_007_SWI_T2star_map_MGE_E7_dn4.nii.gz --use-NN

# Thresholds the cortex
fslmaths 7_003_labels_warped.nii.gz -bin -mul ../7_007_SWI_T2star_map_MGE_E7_dn4.nii.gz 7_007_SWI_T2star_cortex.nii.gz

# ------------------------------------------------------------------------------------------------------------
# Checar corregistros al atlas
slicesdir -p /mnt/Data/RAT_fMRI/Templates_Rat/TohokuUniv/brain.nii.gz $(ls */*_2TohokuA.nii.gz)
rm -rf slicesdir_T2toAtlas; mv slicesdir/ slicesdir_T2toAtlas
